name: Feature Suggestion
description: Suggest a Feature
title: "FEATURE NAME HERE"
labels: ["Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!
  - type: input
    id: contact
    attributes:
      label: Discord Info
      description: |
        (OPTIONAL) How can we get in touch with you if we need more info?
        
        If this is being submitted on behalf of someone, provide their info here
      placeholder: ex. fisher#8036
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: What would this do?
      description: Please be detailed, and how would it worked
      placeholder: How would this feature work?
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What priority do you see this feature as?
      options:
        - IMMEDIATE!
        - High Priority, would be greatly needed
        - Medium Priority, it would be nice to have it soon
        - Low Priority, just an idea that does not need to be added anytime soon
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: By submitting this suggestion, you agree that you are not submitting spam, troll, or fake suggestions.
      options:
        - label: I agree to follow and abide by the above statement
          required: true
